### PR TITLE
Ref: Add stuff from ideas.txt

### PR DESCRIPTION
**Pull request by Jeyveen7**
- [website-popup-cli](https://github.com/sindresorhus/website-popup-cli) - Quickly watch a window in a pop up window without closing or opening another full screen window.

### CODE REVIEW

**Comment by aharris88** [comment]
Can you also remove this from the `ideas.txt` file?

**Comment by Jeyveen7** [comment]
Sure, done.

**Comment by aharris88** [comment]
Ok, I see that you did it in #76, which is fine, but since there are merge conflicts, can you fix the merge conflicts and then just add another commit to the existing pull request, or edit the commit to the exiting pull request (you'll have to `git push --force` in that case)?

**Comment by Jeyveen7** [comment]
It says: This branch has conflicts that must be resolved. Only those with write access to this repository can merge pull requests.

**Comment by aharris88** [comment]
You could resolve it since you have write access to your branch, but I can do it later today. If you have time, you might try looking up how to resolve a merge conflict.

**Pull request merged**
