### PR TITLE
Add nehm

### PR DESCRIPTION
**Pull request by bogem**
This app was created by myself and I think it can help for many SoundCloud users :)

### CODE REVIEW

**Comment by aharris88** [comment]
I don't have anything in my iTunes library, so I haven't had a chance yet to check this out. But I'll see if I can get anyone to test it out for me and see if it's awesome. In the meantime, anybody who thinks [nehm](https://github.com/bogem/nehm) is awesome can comment here and let me know.

**Comment by bogem** [comment]
@aharris88 But it can also work good without iTunes. The feature, which adds all downloaded tracks to iTunes, is optional.

**Comment by aharris88** [comment]
Ok, I just don't have any music, but I'll see if I can try it out soon.

**Comment by aharris88** [comment]
If anyone has tried nehm, let me know if I should add it to the list.

**Comment by bogem** [comment]
Please🙏

**Comment by bogem** [comment]
Fixed

**Comment by bogem** [comment]
Thanks!

**Pull request merged**
