### PR TITLE
Add calories

### PR DESCRIPTION
**Pull request by zupzup**
Calories is a commandline tool for tracking calories and weight using the Harris Benedict formula for calculating your BMR (Basal Metabolic Rate).

I haven't found many health-related tools on the list yet, so I thought it might be a good fit.

[https://github.com/zupzup/calories](https://github.com/zupzup/calories)

### CODE REVIEW

**Comment by aharris88** [comment]
Looks cool. How does it store the data? Plain text? Database?

**Comment by zupzup** [comment]
It uses [boltdb](https://github.com/boltdb/bolt) for persistence :)

**Comment by aharris88** [comment]
Cool. Is the `.db` file human readable (plain text)? or a binary file?

**Comment by zupzup** [comment]
It's not human-readable per se, but inspecting the raw text gives some hints about the data. The database is browsable though with some of bolt's tools.
The tool also has a full JSON export/import, that's probably more human-readable :)

**Pull request merged**
