### PR TITLE
add dev-time

### PR DESCRIPTION
**Pull request by SamVerschueren**
Added [dev-time](https://github.com/samverschueren/dev-time-cli) to the utilities list. Not sure if it's the correct section though, didn't knew where else to put it.

### CODE REVIEW

**Comment by aharris88** [comment]
I think you should put it under git. Can you update this pull request?

**Comment by SamVerschueren** [comment]
Sure, will do it later today.

**Comment by SamVerschueren** [comment]
Fixed

**Comment by aharris88** [comment]
Thanks!

**Comment by SamVerschueren** [comment]
Thanks for merging!

**Pull request merged**
