### PR TITLE
New terminal utilities section

### PR DESCRIPTION
**Pull request by Moshe-Immerman**

### CODE REVIEW

**Comment by aharris88** [comment]
I'm not sure if I want to start adding terminal emulators (iTerm, Upterm, Hyper), but the other stuff looks cool.

**Comment by Moshe-Immerman** [comment]
@aharris88 removed terminals - please squash commits

**Comment by aharris88** [comment]
Need to add the new section to the table of contents at the top.

**Comment by aharris88** [comment]
And maybe add this one while you're in there: https://github.com/spolu/warp

**Comment by Moshe-Immerman** [comment]
@aharris88 done

**Pull request merged**
