### PR TITLE
Add itunes-remote

### PR DESCRIPTION
**Pull request by mischah**
This is an app coded by myself and fun to use :smile:

### CODE REVIEW

**Comment by aharris88** [comment]
Since this is OS X only, that brings up a good point. Do we want to have a separate section for OS X only? or maybe we could differentiate them somehow? maybe put some symbol next to anything that is OS X only?

**Comment by aharris88** [comment]
It's really cool!

**Comment by mischah** [comment]
> It's really cool!

Thanks. Yeah I enjoy using it 😊

>  Do we want to have a separate section for OS X only? or maybe we could differentiate them somehow? maybe put some symbol next to anything that is OS X only?

A symbol would be nice:
* [ only] [itunes-remote](https://github.com/mischah/itunes-remote)  - It’s about listening to music without leaving the terminal.

But the problem is that their might be Windows only tools. And I don’t find a windows symbol over here:  http://www.copypastecharacter.com/symbols

Or don’t we add Windows only tools? :laughing: 

We also could do something like this:
*  [itunes-remote](https://github.com/mischah/itunes-remote) [:grey_exclamation:OS X only ] - It’s about listening to music without leaving the terminal.

> Do we want to have a separate section for OS X only?

I don’t think so. I would love to have categories by purpose.
I would rename the current category »OS X« to something like »OS related«

**Comment by aharris88** [comment]
Sounds good. I like the Apple symbol, but I would probably put it after the name like this:

*[itunes-remote](https://github.com/mischah/itunes-remote) ( only)- It’s about listening to music without leaving the terminal.

**Comment by aharris88** [comment]
I don't know any Windows only tools. I wouldn't be able to test them out anyway.

**Pull request merged**
