### PR TITLE
added trelew

### PR DESCRIPTION
**Pull request by fiatjaf**

### CODE REVIEW

**Comment by dthree** [comment]
:+1:

**Comment by aharris88** [comment]
Looks awesome. It doesn't have a lot of history or stars yet. That's not a big deal, but I want to make sure that it really is awesome before I add it to the list. I tried it out myself and got an error, so I submitted an issue: https://github.com/websitesfortrello/trelew/issues/12

**Comment by fiatjaf** [comment]
Yes, you're right. I forgot that it should be awesome. Also, it is still uncomplete, let's wait until it's more mature, has had its bugs fixed and perhaps has more stars.

**Comment by aharris88** [comment]
Ok, I'll close this for now. Ping me when you're ready.

**Pull request closed without merging**
