### PR TITLE
Added moviemon under Entertainment

### PR DESCRIPTION
**Pull request by iCHAIT**

### CODE REVIEW

**Comment by aharris88** [comment]
I tried installing it (to make sure that it's awesome), and I had a problem, so I [submitted an issue](https://github.com/iCHAIT/moviemon/issues/1).

**Comment by iCHAIT** [comment]
@aharris88 I have left a comment on the issue, can you try that?

**Comment by aharris88** [comment]
I'm having trouble trying this out. If anyone wants to try it out, let me know if you were able to use it and if you think I should add it to the list.

**Comment by dufferzafar** [comment]
:+1:

**Comment by iCHAIT** [comment]
@aharris88 Interested in merging this?

**Pull request merged**
