### PR TITLE
Add Cash: Cross-platform Linux commands in pure ES6

### PR DESCRIPTION
**Pull request by dthree**
[Cash](https://github.com/dthree/cash) implements popular Unix / Linux commands such as `ls`, `grep` `less` using straight ES6, installed through Node.

### CODE REVIEW

**Comment by aharris88** [comment]
Thanks! That's really cool.

**Comment by dthree** [comment]
Thanks! :+1:

**Comment by aharris88** [comment]
I also added your Wat to the list!

**Comment by dthree** [comment]
Yikes!! It's not released, so I really would rather not, but I really do appreciate that gesture, thank you!

**Comment by aharris88** [comment]
Sorry, I tried it out and it seems to work really well! It has over 200 stars, it's listed on npm, and it says it's scheduled for imminent release, so I thought it must be pretty stable. Also, if it doesn't work, people can just look up the info elsewhere.

But, if you want me to remove it from this list, I will until you're ready.

**Comment by dthree** [comment]
That was really nice of you. 

What I have published at NPM works, I guess, however I have a ton of work and refactoring to do on auto-document generation so that it scales. Haven't had a chance to release due to this.

I guess since it works, we can leave it. If I get too many issues I'll let you know.

:+1:

**Pull request merged**
