### PR TITLE
Add doing & more

### PR DESCRIPTION
**Pull request by herrbischoff**
Add doing and a couple of other tools for your consideration.

### CODE REVIEW

**Comment by aharris88** [comment]
Thanks! I forgot about Taskwarrior! btw, do you think it's better to use dashes or stars for the list? I noticed that sindresorhus uses dashes for his lists. I'm totally open to use dashes if that's what most people use for lists.

**Comment by herrbischoff** [comment]
I found that most Awesome lists use dashes. Also, I will merge the changes so you can merge this pull request automatically.

**Comment by herrbischoff** [comment]
All done.

**Comment by aharris88** [comment]
Thanks!

**Comment by herrbischoff** [comment]
:ok_hand:

**Pull request merged**
